#!/bin/bash

BASE_TAG=corso/hadoop
TAG_IMAGE=hadoop3.3.6-java8

DOCKER_NETWORK=net-cloudera
ENV_FILE=hadoop.env

VOL_BASE_NAME=vol-hadoop
VOL_NAMENODE=$VOL_BASE_NAME-namenode
VOL_DATANODE=$VOL_BASE_NAME-datanode
VOL_HISTORYSERVER=$VOL_BASE_NAME-historyserver

CLUSTER_NAME=HadoopTest

CNT_BASE_NAME=hadoop
CNT_NAMENODE=$CNT_BASE_NAME-namenode
CNT_DATANODE=$CNT_BASE_NAME-datanode
CNT_RESOURCEMANAGER=$CNT_BASE_NAME-resourcemanager
CNT_MODEMANAGER=$CNT_BASE_NAME-nodemanager
CNT_HISTORYSERVER=$CNT_BASE_NAME-historyserver